<?php

/*
 * The app's own label for every menu item, button and option the site names
 * in a <ui> tag, in the languages the app is translated into: the Mac app in
 * French, Korean and both Chinese scripts, the iPhone app in Korean and both
 * Chinese scripts. Taken from the apps' string catalogs
 * (TablePro/Resources/Localizable.xcstrings and TableProMobile's).
 *
 * A language missing from a row means the app shows that label in English
 * there. So does an empty row: a driver's own field, another product's menu,
 * or a label the catalog does not translate yet.
 */

return [
    'Account > D1 > Edit' => [],
    'Add Row' => ['fr' => 'Ajouter une ligne', 'ko' => '행 추가', 'zh-Hans' => '添加行', 'zh-Hant' => '新增列'],
    'Additional Bootstrap Servers' => ['fr' => 'Serveurs bootstrap supplémentaires', 'ko' => '추가 부트스트랩 서버', 'zh-Hans' => '额外的 Bootstrap 服务器', 'zh-Hant' => '額外的 Bootstrap 伺服器'],
    'Always Allow' => ['fr' => 'Toujours autoriser', 'ko' => '항상 허용', 'zh-Hans' => '始终允许', 'zh-Hant' => '永遠允許'],
    'API Token' => ['fr' => 'Jeton API', 'ko' => 'API 토큰'],
    'Application Default Credentials' => ['fr' => 'Identifiants par défaut de l’application', 'ko' => '애플리케이션 기본 사용자 인증 정보'],
    'Apply to Editor' => ['fr' => 'Appliquer à l’éditeur', 'ko' => '편집기에 적용', 'zh-Hans' => '应用到编辑器', 'zh-Hant' => '套用到編輯器'],
    'Auth Database' => [],
    'Auth Level' => ['fr' => 'Niveau d’authentification', 'ko' => '인증 수준', 'zh-Hans' => '认证级别', 'zh-Hant' => '驗證層級'],
    'Auth Method' => ['fr' => 'Méthode d’authentification', 'ko' => '인증 방식', 'zh-Hans' => '认证方式', 'zh-Hant' => '驗證方式'],
    'Authentication' => ['fr' => 'Authentification', 'ko' => '인증', 'zh-Hans' => '身份验证', 'zh-Hant' => '身分驗證'],
    'AWS Region' => ['fr' => 'Région AWS', 'ko' => 'AWS 리전', 'zh-Hans' => 'AWS 区域', 'zh-Hant' => 'AWS 區域'],
    'Broker Addresses' => ['fr' => 'Adresses des brokers', 'ko' => '브로커 주소', 'zh-Hans' => 'Broker 地址', 'zh-Hant' => 'Broker 位址'],
    'Browse…' => ['fr' => 'Parcourir…', 'ko' => '찾아보기…', 'zh-Hans' => '浏览…', 'zh-Hant' => '瀏覽…'],
    'CA Certificate' => ['fr' => 'Certificat d’autorité (CA)', 'ko' => 'CA 인증서', 'zh-Hans' => 'CA 证书', 'zh-Hant' => 'CA 憑證'],
    'Catalog' => [],
    'CLI Connection Name' => ['fr' => 'Nom de connexion CLI', 'ko' => 'CLI 연결 이름', 'zh-Hans' => 'CLI连接名称', 'zh-Hant' => 'CLI 連線名稱'],
    'Connection Mode' => ['fr' => 'Mode de connexion', 'ko' => '연결 모드', 'zh-Hans' => '连接模式', 'zh-Hant' => '連線模式'],
    'Connection Type' => ['fr' => 'Type de connexion', 'ko' => '연결 유형', 'zh-Hans' => '连接类型', 'zh-Hant' => '連線類型'],
    'Continue' => ['fr' => 'Continuer', 'ko' => '계속', 'zh-Hans' => '继续', 'zh-Hant' => '繼續'],
    'Count Exactly' => ['fr' => 'Compter exactement', 'ko' => '정확히 계산', 'zh-Hans' => '精确计数', 'zh-Hant' => '精確計算'],
    'Custom Endpoint' => ['fr' => 'Point de terminaison personnalisé', 'ko' => '사용자 지정 엔드포인트', 'zh-Hans' => '自定义端点', 'zh-Hant' => '自訂端點'],
    'Database' => ['fr' => 'Base de données', 'ko' => '데이터베이스', 'zh-Hans' => '数据库', 'zh-Hant' => '資料庫'],
    'Database > Release File Lock' => ['fr' => 'Base de données > Libérer le verrou du fichier', 'ko' => '데이터베이스 > Release File Lock', 'zh-Hans' => '数据库 > Release File Lock', 'zh-Hant' => '資料庫 > Release File Lock'],
    'Database > Session Context' => ['fr' => 'Base de données > Contexte de session', 'ko' => '데이터베이스 > Session Context', 'zh-Hans' => '数据库 > Session Context', 'zh-Hant' => '資料庫 > Session Context'],
    'Dry Run (Cost)' => [],
    'Duplicate Row' => ['fr' => 'Dupliquer la ligne', 'ko' => '행 복제', 'zh-Hans' => '复制行', 'zh-Hant' => '複製列'],
    'DynamoDB Local (no credentials)' => ['fr' => 'DynamoDB Local (sans identifiants)'],
    'Export Password' => [],
    'Export Results' => ['fr' => 'Exporter les résultats', 'ko' => '결과 내보내기', 'zh-Hans' => '导出结果', 'zh-Hant' => '匯出結果'],
    'File > Export Connections…' => [],
    'File > Import > Import from Other App…' => ['fr' => 'Fichier > Importer > Importer depuis une autre app…', 'ko' => '파일 > 가져오기 > 다른 앱에서 가져오기…', 'zh-Hans' => '文件 > 导入 > 从其他应用导入…', 'zh-Hant' => '檔案 > 匯入 > 從其他 App 匯入…'],
    'File > Import > Import from URL…' => ['fr' => 'Fichier > Importer > Importer depuis une URL…', 'ko' => '파일 > 가져오기 > URL에서 가져오기…', 'zh-Hans' => '文件 > 导入 > 从 URL 导入…', 'zh-Hant' => '檔案 > 匯入 > 從 URL 匯入…'],
    'File > Import > Open Project Folder…' => ['fr' => 'Fichier > Importer > Ouvrir le dossier du projet…', 'ko' => '파일 > 가져오기 > 프로젝트 폴더 열기…', 'zh-Hans' => '文件 > 导入 > 打开项目文件夹…', 'zh-Hant' => '檔案 > 匯入 > 開啟專案資料夾…'],
    'File > Open File' => ['fr' => 'Fichier > Ouvrir un fichier', 'ko' => '파일 > 파일 열기', 'zh-Hans' => '文件 > 打开文件', 'zh-Hant' => '檔案 > 開啟檔案'],
    'File > Server-Side Export…' => ['fr' => 'Fichier > Exportation côté serveur…', 'ko' => '파일 > Server-Side Export…', 'zh-Hans' => '文件 > Server-Side Export…', 'zh-Hant' => '檔案 > Server-Side Export…'],
    'Help > Open Sample Database' => ['fr' => 'Aide > Ouvrir la base de données d’exemple', 'ko' => '도움말 > 샘플 데이터베이스 열기', 'zh-Hans' => '帮助 > 打开示例数据库', 'zh-Hant' => '輔助說明 > 開啟範例資料庫'],
    'Import' => ['fr' => 'Importer', 'ko' => '가져오기', 'zh-Hans' => '导入', 'zh-Hant' => '匯入'],
    'Import from AWS' => ['fr' => 'Importer depuis AWS'],
    'Import from Other App' => ['fr' => 'Importer depuis une autre app', 'ko' => '다른 앱에서 가져오기', 'zh-Hans' => '从其他应用导入', 'zh-Hant' => '從其他 App 匯入'],
    'Import from URL…' => ['fr' => 'Importer depuis une URL…', 'ko' => 'URL에서 가져오기…', 'zh-Hans' => '从 URL 导入…', 'zh-Hant' => '從 URL 匯入…'],
    'Import into Table' => ['fr' => 'Importer dans une table'],
    'Include passwords' => ['fr' => 'Inclure les mots de passe', 'ko' => '암호 포함', 'zh-Hans' => '包含密码', 'zh-Hant' => '包含密碼'],
    'Key Prefix Root' => ['fr' => 'Racine du préfixe de clé', 'ko' => '키 접두사 루트', 'zh-Hans' => '键前缀根', 'zh-Hant' => '索引鍵前綴根目錄'],
    'Keys' => ['fr' => 'Clés', 'ko' => '키', 'zh-Hans' => '键', 'zh-Hant' => '鍵'],
    'Local File' => ['fr' => 'Fichier local', 'ko' => '로컬 파일', 'zh-Hans' => '本地文件', 'zh-Hant' => '本機檔案'],
    'Location' => ['fr' => 'Emplacement', 'ko' => '위치', 'zh-Hans' => '位置', 'zh-Hant' => '位置'],
    'Logon Mechanism' => [],
    'Maintenance' => ['ko' => '유지 관리', 'zh-Hans' => '维护', 'zh-Hant' => '維護'],
    'Match by Name' => ['fr' => 'Associer par nom'],
    'Match by Position' => ['fr' => 'Associer par position'],
    'Max Bytes Billed' => ['fr' => 'Octets facturés max.', 'ko' => '최대 청구 바이트', 'zh-Hans' => '最大计费字节数', 'zh-Hant' => '最大計費位元組數'],
    'MFA Passcode (TOTP)' => ['fr' => 'Code MFA (TOTP)', 'ko' => 'MFA 인증 코드(TOTP)', 'zh-Hans' => 'MFA 验证码（TOTP）', 'zh-Hant' => 'MFA 驗證碼（TOTP）'],
    'Move to' => ['fr' => 'Déplacer vers', 'ko' => '다음으로 이동', 'zh-Hans' => '移动到', 'zh-Hant' => '移動至'],
    'Network' => ['fr' => 'Réseau', 'ko' => '네트워크', 'zh-Hans' => '网络', 'zh-Hant' => '網路'],
    'Network Encryption' => [],
    'New Database…' => ['fr' => 'Nouvelle base de données…', 'ko' => '새 데이터베이스…', 'zh-Hans' => '新建数据库…', 'zh-Hant' => '新增資料庫…'],
    'New Table' => ['fr' => 'Nouvelle table', 'ko' => '새 테이블', 'zh-Hans' => '新建表', 'zh-Hant' => '新增資料表'],
    'New Table…' => ['fr' => 'Nouvelle table…', 'ko' => '새 테이블…', 'zh-Hans' => '新建表…', 'zh-Hant' => '新增資料表…'],
    'Open' => ['fr' => 'Ouvrir', 'ko' => '열기', 'zh-Hans' => '打开', 'zh-Hant' => '開啟'],
    'Open in New Window' => ['fr' => 'Ouvrir dans une nouvelle fenêtre', 'ko' => '새 윈도우에서 열기', 'zh-Hans' => '在新窗口中打开', 'zh-Hant' => '在新視窗中開啟'],
    'Open Project Folder' => ['fr' => 'Ouvrir le dossier du projet', 'ko' => '프로젝트 폴더 열기', 'zh-Hans' => '打开项目文件夹', 'zh-Hant' => '開啟專案資料夾'],
    'Open Sample Database' => ['fr' => 'Ouvrir la base de données d’exemple', 'ko' => '샘플 데이터베이스 열기', 'zh-Hans' => '打开示例数据库', 'zh-Hant' => '開啟範例資料庫'],
    'Open the File Read-Only' => ['fr' => 'Ouvrir le fichier en lecture seule'],
    'Password' => ['fr' => 'Mot de passe', 'ko' => '암호', 'zh-Hans' => '密码', 'zh-Hant' => '密碼'],
    'Passwords' => ['fr' => 'Mots de passe', 'ko' => '암호', 'zh-Hans' => '密码', 'zh-Hant' => '密碼'],
    'Preview' => ['fr' => 'Aperçu', 'ko' => '미리보기', 'zh-Hans' => '预览', 'zh-Hant' => '預覽'],
    'Preview SQL' => ['fr' => 'Aperçu SQL', 'ko' => 'SQL 미리보기', 'zh-Hans' => '预览 SQL', 'zh-Hant' => '預覽 SQL'],
    'Project ID' => ['fr' => 'ID du projet', 'ko' => '프로젝트 ID', 'zh-Hans' => '项目 ID', 'zh-Hant' => '專案 ID'],
    'Publish Saved Queries to Team…' => ['fr' => 'Publier les requêtes enregistrées pour l’équipe…', 'ko' => '저장된 쿼리를 팀에 게시…', 'zh-Hans' => '将已保存的查询发布到团队…', 'zh-Hant' => '將已儲存的查詢發佈到團隊…'],
    'Query > Cancel Query' => ['fr' => 'Requête > Annuler la requête', 'ko' => '쿼리 > 쿼리 취소', 'zh-Hans' => '查询 > 取消查询', 'zh-Hant' => '查詢 > 取消查詢'],
    'Refresh' => ['fr' => 'Actualiser', 'ko' => '새로 고침', 'zh-Hans' => '刷新', 'zh-Hant' => '重新整理'],
    'Release the File Lock After' => ['fr' => 'Libérer le verrou du fichier après'],
    'Remote (Quack, experimental)' => ['fr' => 'Distant (Quack, expérimental)', 'ko' => '원격(Quack, 실험적)', 'zh-Hans' => '远程（Quack，实验性）', 'zh-Hant' => '遠端（Quack，實驗性）'],
    'Remote (Turso)' => ['fr' => 'Distant (Turso)', 'ko' => '원격(Turso)', 'zh-Hans' => '远程 (Turso)', 'zh-Hant' => '遠端 (Turso)'],
    'Remove Field' => ['fr' => 'Supprimer le champ'],
    'Restore Previous Values' => ['fr' => 'Restaurer les valeurs précédentes', 'ko' => '이전 값 복원', 'zh-Hans' => '恢复之前的值', 'zh-Hant' => '還原先前的值'],
    'Run Ledger Plugins' => ['fr' => 'Exécuter les plugins Ledger', 'ko' => '원장 플러그인 실행', 'zh-Hans' => '运行账本插件', 'zh-Hant' => '執行帳本外掛'],
    'SASL Mechanism' => ['fr' => 'Mécanisme SASL', 'ko' => 'SASL 메커니즘', 'zh-Hans' => 'SASL 机制', 'zh-Hant' => 'SASL 機制'],
    'Schema' => ['fr' => 'Schéma', 'ko' => '스키마', 'zh-Hant' => '綱要'],
    'Security Protocol' => ['fr' => 'Protocole de sécurité', 'ko' => '보안 프로토콜', 'zh-Hans' => '安全协议', 'zh-Hant' => '安全性協定'],
    'Service Account Key' => ['fr' => 'Clé du compte de service', 'ko' => '서비스 계정 키', 'zh-Hans' => '服务账号密钥', 'zh-Hant' => '服務帳戶金鑰'],
    'Set NULL' => ['fr' => 'Définir sur NULL', 'ko' => 'NULL로 설정', 'zh-Hans' => '设为 NULL', 'zh-Hant' => '設為 NULL'],
    'Settings > AI' => ['fr' => 'Réglages > IA', 'ko' => '설정 > AI', 'zh-Hans' => '设置 > AI', 'zh-Hant' => '設定 > AI'],
    'Settings > Editor > Vim mode' => ['fr' => 'Réglages > Éditeur > Mode Vim', 'ko' => '설정 > 편집기 > Vim 모드', 'zh-Hans' => '设置 > 编辑器 > Vim 模式', 'zh-Hant' => '設定 > 編輯器 > Vim 模式'],
    'Settings > General' => ['fr' => 'Réglages > Général', 'ko' => '설정 > 일반', 'zh-Hans' => '设置 > 通用', 'zh-Hant' => '設定 > 一般'],
    'Settings > General > Privacy' => ['fr' => 'Réglages > Général > Confidentialité', 'ko' => '설정 > 일반 > 개인정보 보호', 'zh-Hans' => '设置 > 通用 > 隐私', 'zh-Hant' => '設定 > 一般 > 隱私'],
    'Settings > Integrations' => ['fr' => 'Réglages > Intégrations', 'ko' => '설정 > 통합', 'zh-Hans' => '设置 > 集成', 'zh-Hant' => '設定 > 整合'],
    'Settings > License' => ['fr' => 'Réglages > Licence', 'ko' => '설정 > 라이선스', 'zh-Hans' => '设置 > 许可证', 'zh-Hant' => '設定 > 授權'],
    'Settings > Live Activities > Hide Query' => ['ko' => '설정 > 실시간 현황 > 쿼리 가리기', 'zh-Hans' => '设置 > 实时活动 > 隐藏查询', 'zh-Hant' => '設定 > 即時動態 > 隱藏查詢'],
    'Settings > Plugins' => ['fr' => 'Réglages > Plugins', 'ko' => '설정 > 플러그인', 'zh-Hans' => '设置 > 插件', 'zh-Hant' => '設定 > 外掛'],
    'Settings > Privacy' => ['ko' => '설정 > 개인정보 보호', 'zh-Hans' => '设置 > 隐私', 'zh-Hant' => '設定 > 隱私權'],
    'Settings > Security' => ['ko' => '설정 > 보안', 'zh-Hans' => '设置 > 安全', 'zh-Hant' => '設定 > 安全性'],
    'Share > Publish to Team Catalog…' => ['fr' => 'Partager > Publier dans le catalogue d’équipe…', 'ko' => '공유 > 팀 카탈로그에 게시…', 'zh-Hans' => '分享 > 发布到团队目录…', 'zh-Hant' => '分享 > 發佈到團隊目錄…'],
    'Share > Publish to Team Library…' => ['fr' => 'Partager > Publier dans la bibliothèque d’équipe…', 'ko' => '공유 > 팀 라이브러리에 게시…', 'zh-Hans' => '分享 > 发布到团队库…', 'zh-Hant' => '分享 > 發佈到團隊庫…'],
    'Sync Passwords' => ['ko' => '암호 동기화', 'zh-Hans' => '同步密码', 'zh-Hant' => '同步密碼'],
    'TablePro > Check for Updates…' => ['fr' => 'TablePro > Rechercher les mises à jour…', 'ko' => 'TablePro > 업데이트 확인…', 'zh-Hans' => 'TablePro > 检查更新…', 'zh-Hant' => 'TablePro > 檢查更新…'],
    'Terminate Session' => ['fr' => 'Mettre fin à la session', 'ko' => '세션 종료', 'zh-Hans' => '终止会话', 'zh-Hant' => '終止工作階段'],
    'Time Zone' => ['fr' => 'Fuseau horaire', 'ko' => '시간대', 'zh-Hans' => '时区', 'zh-Hant' => '時區'],
    'TLS Mode' => ['fr' => 'Mode TLS', 'ko' => 'TLS 모드', 'zh-Hans' => 'TLS 模式', 'zh-Hant' => 'TLS 模式'],
    'Transaction Mode' => [],
    'Use clipboard URL' => ['fr' => 'Utiliser l’URL du presse-papiers', 'ko' => '클립보드 URL 사용', 'zh-Hans' => '使用剪贴板中的 URL', 'zh-Hant' => '使用剪貼簿中的 URL'],
    'Username' => ['fr' => 'Nom d’utilisateur', 'ko' => '사용자 이름', 'zh-Hans' => '用户名', 'zh-Hant' => '使用者名稱'],
    'View > Sidebar as Tree' => ['fr' => 'Présentation > Barre latérale en arborescence', 'ko' => '보기 > 트리형 사이드바', 'zh-Hans' => '视图 > 侧边栏显示为树状', 'zh-Hant' => '檢視 > 側邊欄顯示為樹狀'],
    'View ER Diagram' => ['fr' => 'Afficher le diagramme entité-relation', 'ko' => 'ER 다이어그램 보기', 'zh-Hans' => '查看 ER 图', 'zh-Hant' => '檢視 ER 圖'],
    'Warehouse' => ['fr' => 'Entrepôt', 'ko' => '웨어하우스', 'zh-Hans' => '仓库', 'zh-Hant' => '倉儲'],
];
